# download ngc cli
- name: Download NGC CLI
  get_url:
    url: https://ngc.nvidia.com/downloads/ngccli_cat_linux.zip
    dest: "/tmp/ngccli_cat_linux.zip"
    force: yes

# extract ngc cli
- name: Extract NGC CLI
  unarchive:
    src: "/tmp/ngccli_cat_linux.zip"
    dest: "/opt"
    remote_src: yes

# add path to ngc cli to bashrc
- name: Add NGC CLI to PATH
  lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    line: "export PATH=$PATH:/opt/ngc-cli"
    create: yes
    state: present

# make sure /home/ubuntu/.ngc exists
- name: Create NGC CLI config directory
  file:
    path: "/home/{{ ansible_user }}/.ngc"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  tags: _ngc_cli_config

# configure ngc cli (upload template file)
- name: Configure NGC CLI
  template:
    src: "ngc_cli.conf"
    dest: "/home/{{ ansible_user }}/.ngc/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600
  tags: _ngc_cli_config
