# region copyright
# Copyright 2023 NVIDIA Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# endregion

---
- name: Add Docker apt key
  apt_key: url="https://download.docker.com/linux/ubuntu/gpg"
    state=present

- name: Add Docker apt package repository
  apt_repository:
    repo="deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state=present
    mode=644

- name: Install docker packages
  apt: name={{ item }}
    state=latest
    update_cache=yes
  with_items:
    - docker-ce
    - docker-ce-cli

- name: Create docker group
  group: name=docker
    state=present

- name: Add user ubuntu to docker group
  user: name=ubuntu
    groups=docker
    append=yes
    state=present

- name: Reset connection so docker group is picked up
  meta: reset_connection

- name: Install docker-compose
  get_url:
    url="https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}"
    dest=/usr/local/bin/docker-compose
    force=no
    mode=755
